#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.datasource.url=jdbc:postgresql://localhost:3006/postgres
spring.datasource.username=postgres
spring.datasource.password=123

security.encryption.key=abcde1234567890f

security.jwt.secret=547677afbc8db9e2e62c601cd3bb1b6f

app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173